### ISSUE TITLE
Get Database 404s

### ISSUE THREAD

**Issue by sachit-menon** [modestyachts/imagenet-testbed#1]
Hi, thank you for this repo. I was trying to run the example evaluation and the database download seems to 404. Is there a correct link, or is there some way for me to work around this? 

`downloading database dump...
--2020-12-07 14:11:06--  https://robustness-eval.s3-us-west-2.amazonaws.com/robustness_evaluation.db
Resolving robustness-eval.s3-us-west-2.amazonaws.com (robustness-eval.s3-us-west-2.amazonaws.com)... 52.218.209.121
Connecting to robustness-eval.s3-us-west-2.amazonaws.com (robustness-eval.s3-us-west-2.amazonaws.com)|52.218.209.121|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-12-07 14:11:06 ERROR 404: Not Found.

Traceback (most recent call last):
  File "eval.py", line 11, in <module>
    registry.load_full_registry()
  File "src/registry.py", line 23, in load_full_registry
    import_module(f'models.{f.stem}')
  File "/home/sachit/miniconda3/envs/robustness/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "src/models/antialiased.py", line 3, in <module>
    from mldb.utils import load_model_state_dict
  File "src/mldb/utils.py", line 11, in <module>
    m_repo = model_repository.ModelRepository()
  File "src/mldb/model_repository.py", line 265, in __init__
    download_db()
  File "src/mldb/model_repository.py", line 30, in download_db
    subprocess.run(['wget', '-P', s3_utils.default_cache_root_path, DB_DUMP_URL], check=True)
  File "/home/sachit/miniconda3/envs/robustness/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['wget', '-P', PosixPath('/proj/vondrick/sachit/projects/robustness/imagenet-testbed/s3_cache'), 'https://robustness-eval.s3-us-west-2.amazonaws.com/robustness_evaluation.db']' returned non-zero exit status 8.`

**Comment by ludwigschmidt** [comment]
Hi Sachit, thanks for reaching out. We migrated our database to a new back-end over the last week. The link should be back shortly.

**Comment by sachit-menon** [comment]
Great, and thank you for the quick response! I will try again later today.  
(BTW, I came here after your wonderful talk 'at' Columbia a few weeks ago - thank you for that as well.)

**Comment by rtaori** [comment]
Hi Sachit,
Thanks for opening this issue. The migration has now been completed, so everything should be working as normal :) 
Just make sure to pull from master again. Let us know if you're having any other issues.

**Comment by sachit-menon** [comment]
Hi Rohan, I confirmed it downloads properly now. The repo seems to work great! Thanks, I'll close this issue and make another one if something else comes up.
