### ISSUE TITLE
ClientError: Access Denied.   When  persist the results of models in the db

### ISSUE THREAD

**Issue by Yangyi-Chen** [modestyachts/imagenet-testbed#4]
Hi, thanks for this fantastic repo. 
But, when I try to persis the results of my models in the db (i 've already add the model to db through python db.py --add-model model),  I run  python eval.py --gpus 0 --models MyModel  --eval-settings imagenet-a  --db
Then, error occurs: 

`Traceback (most recent call last):
  File "/data3/private/chenyangyi/imagenet-testbed-master/src/mldb/s3_utils.py", line 326, in put_s3_object_bytes_with_backoff
    client.upload_fileobj(bio, Key=key, Bucket=bucket, ExtraArgs={'ACL': 'bucket-owner-full-control'})
  File "/data3/private/chenyangyi/imagenet-testbed-master/robustness/lib/python3.6/site-packages/boto3/s3/inject.py", line 539, in upload_fileobj
    return future.result()
  File "/data3/private/chenyangyi/imagenet-testbed-master/robustness/lib/python3.6/site-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/data3/private/chenyangyi/imagenet-testbed-master/robustness/lib/python3.6/site-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
  File "/data3/private/chenyangyi/imagenet-testbed-master/robustness/lib/python3.6/site-packages/s3transfer/tasks.py", line 126, in __call__
    return self._execute_main(kwargs)
  File "/data3/private/chenyangyi/imagenet-testbed-master/robustness/lib/python3.6/site-packages/s3transfer/tasks.py", line 150, in _execute_main
    return_value = self._main(**kwargs)
  File "/data3/private/chenyangyi/imagenet-testbed-master/robustness/lib/python3.6/site-packages/s3transfer/upload.py", line 692, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "/data3/private/chenyangyi/imagenet-testbed-master/robustness/lib/python3.6/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/data3/private/chenyangyi/imagenet-testbed-master/robustness/lib/python3.6/site-packages/botocore/client.py", line 635, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/inference.py", line 134, in <module>
    main(args)
  File "src/inference.py", line 44, in main
    utils.store_evaluation(py_model, py_eval_setting, metrics, logits)
  File "/data3/private/chenyangyi/imagenet-testbed-master/src/mldb/utils.py", line 57, in store_evaluation
    extra_info=metrics, logits_data_bytes=bio.getvalue(), completed=True)
  File "/data3/private/chenyangyi/imagenet-testbed-master/src/mldb/model_repository.py", line 718, in create_evaluation
    self.s3wrapper.put(logits_data_bytes, key, verbose=verbose)
  File "/data3/private/chenyangyi/imagenet-testbed-master/src/mldb/s3_utils.py", line 541, in put
    delay_factor=self.delay_factor)
  File "/data3/private/chenyangyi/imagenet-testbed-master/src/mldb/s3_utils.py", line 331, in put_s3_object_bytes_with_backoff
    raise Exception('put backoff failed ' + key + ' ' + str(len(file_bytes))+ ' ' + str(delay))
Exception: put backoff failed evaluations/QJ7LR7SaqX_logits_data.bytes 6000754 4.000000000000001`

**Comment by rtaori** [comment]
Hi @Yangyi-Chen ,

Thanks for bringing this issue to our attention. Indeed this is a bug - the library is attempting to upload the pickled logits to the global bucket, which it doesn't have permission for. It was an oversight, and I have removed this call in the latest commit. You can still find the logits pickle locally in the log directory after running an evaluation (the log directory will be printed out onto the console). 

The issue should be resolved now! Please let me know if there are still any inconsistencies or any other issues I can help with.

**Comment by Yangyi-Chen** [comment]
Great ! thanks for helping me out
